# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedQuestion',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('chm.question',),
        ),
        migrations.AlterField(
            model_name='flag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='chm.Question'),
        ),
    ]
