# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0003_xmlfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlfile',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
