# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0004_xmlfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmlfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='xmlfile',
            name='topic',
        ),
    ]
