# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0006_auto_20161027_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='nr_of_questions',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
