# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0008_auto_20161029_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='state',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('finished', 'finished'), ('aborted', 'aborted')], default='in_progress', max_length=20),
        ),
    ]
