# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0009_quiz_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chm.Question'),
        ),
        migrations.AlterField(
            model_name='questiononquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chm.Quiz'),
        ),
    ]
