# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0010_auto_20161105_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='number_ranked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='rank_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='chm.Subject'),
        ),
    ]
