# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0011_auto_20161120_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='number_ranked',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='rank_score',
        ),
        migrations.AddField(
            model_name='question',
            name='number_ranked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='rank_score',
            field=models.IntegerField(default=0),
        ),
    ]
