# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0012_auto_20161120_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rank_score',
        ),
        migrations.AddField(
            model_name='question',
            name='ranked_score',
            field=models.IntegerField(default=0),
        ),
    ]
