# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chm', '0013_auto_20161120_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ranked_score',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='real_difficulty',
            field=models.FloatField(default=1.0),
        ),
    ]
